### ISSUE TITLE
inithist and threading

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [PeterHjortLauritzen/opt-se-cslam#24]
inithist makesuse of fvm2dyn. Currently the fvm2dyn makes use of a ntreads=num_horz_thread buffer but inihist is call from a non-threaded area of the code (see step_on.F90)

**Comment by johnmauff** [comment]
I have fixed  this issue in my development sandbox.  Is this causing a problem with your debugging efforts?

**Comment by PeterHjortLauritzen** [comment]
Issue resolved. 

That said, do you think there could be a speed-up by using threading in the mapping from dynamics to physics and physcs to dynamics in fvm_mapping.F90?

**Comment by johnmauff** [comment]
Peter,

   My plan is once the threading is functioning correctly, I will start to
look at performance optimization.  I suspect that threading the dynamics to
physics and physics to dynamics mapping will be a good idea.

John
