### ISSUE TITLE
possible vertical remap bug

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [PeterHjortLauritzen/opt-se-cslam#25]
When I was running CSLAM with DEBUG set, the bounds checker found bounds 
violation for the variable pio(kk) in line 536 of file vertremap_mod.F90.   I 'fixed' this issue by 
replacing lines 527-529 with the following:

       do while ( pio(kk) <= pin(k+1) )
          kk = kk + 1
          if(kk==nlev+2) exit
        enddo

**Comment by johnmauff** [comment]
Totally forgot about this issue.  Sorry that I did not commit it previously.

**Comment by PeterHjortLauritzen** [comment]
code has been checked in. It is unclear to me why "if(kk==nlev+2) exit" fixes the problem since pio(nlev+2) is guaranteed to be > pin(k+1) so we will always be done with the while-loop with kk<=nlev+2. I have checked that kk is in bounds after the while-loop and it always is. So why "if(kk==nlev+2) exit" is needed is a mystery to me ....

Crash does not happen on Hobart with NAG. Could it be a weird Intel compiler bug.
