### ISSUE TITLE
Eaton had problem with ncdata stability with ne30np4

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [PeterHjortLauritzen/opt-se-cslam#33]

**Comment by brian-eaton** [comment]
I went back to check this test and I see that I didn't use the latest  ncdata file that you had provided.  So I'm rerunning with that file when cheyenne comes back.  The test was with FW2000climo on grid ne30_ne30_mg17 with --pecount set to 216x1.

FYI I copied that file to a standard location and renamed:
> /glade/p/cgd/amp/pel/inic/waccm.i.spinup.nc
copied to: 
/glade/p/cesmdata/cseg/inputdata/atm/waccm/ic/
waccm-tsmlt-mam4_2000_ne30np4_L70_0002-01-01_c181221.nc'

**Comment by brian-eaton** [comment]
I have rerun this test with the spunup IC file and am getting the following failure:

 NEGATIVE LAYER THICKNESS DIAGNOSTICS:
  
 (lon,lat) =  71.17 40.44
  
k,dp_star_moist,u,v,T    1 0.00016256  172.04  -49.12  530.20
...
 ERROR: negative moist layer thickness.  timestep or remap time too large
Image              PC                Routine            Line        Source             
cesm.exe           000000000B2884BD  Unknown               Unknown  Unknown
cesm.exe           000000000A5781A1  shr_abort_mod_mp_         114  shr_abort_mod.F90
cesm.exe           000000000A578022  shr_abort_mod_mp_          61  shr_abort_mod.F90
cesm.exe           0000000004BF8780  prim_advection_mo        1053  prim_advection_mod.F90
cesm.exe           0000000001242171  prim_driver_mod_m         282  prim_driver_mod.F90
cesm.exe           0000000000A8D063  dyn_comp_mp_dyn_r         986  dyn_comp.F90

**Comment by PeterHjortLauritzen** [comment]
Got it ... fixed with se_nsplit=12 change for ne30_ne30
